dist: trusty

language: cpp

sudo: required

compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi

cache:
  directories:
    - libs

script: bash travisbuild.sh