#pragma once

#include <algorithm>
#include <array>
#include <chrono>
#include <csignal>
#include <cstdint>
#include <deque>
#include <fstream>
#include <forward_list>
#include <functional>
#include <future>
#include <initializer_list>
#include <iostream>
#include <list>
#include <map>
#include <memory>
#include <mutex>
#include <thread>
#include <type_traits>
#include <typeindex>
#include <typeinfo>
#include <set>
#include <sstream>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <boost/asio.hpp>
#include <boost/chrono.hpp>
#include <boost/date_time/posix_time/posix_time.hpp>
#include <boost/date_time/posix_time/ptime.hpp>
#include <boost/endian/arithmetic.hpp>
#include <boost/endian/conversion.hpp>
#include <boost/filesystem.hpp>
#include <boost/format.hpp>
#include <boost/optional.hpp>
#include <boost/scoped_array.hpp>
#include <boost/thread.hpp>

#include <json.hpp>